catalogapi_dbhost = "catalog-api-database_dev_01-01"
catalogapi_dbport = "5432"
catalogapi_database = "catalog_api"
catalogapi_dbschema = "catalog"
catalogapi_dbuser = "catalogapi_user"
catalogapi_dbpassword = "123456"
